# ===========================================
# SURREALDB BACKUP SERVICE
# ===========================================

services:
  surrealdb-backup:
    build:
      context: ../../components/surrealdb-backup
      dockerfile: Dockerfile
    image: synology-nas/surrealdb-backup:latest
    container_name: surrealdb-backup
    restart: unless-stopped

    depends_on:
      doppler-core:
        condition: service_healthy
      surrealdb:
        condition: service_healthy

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - SURREALDB_ENDPOINT=${SURREALDB_ENDPOINT:-http://surrealdb:8000}
      - HEALTH_CHECK_PORT=8080

    ports:
      - "${SURREALDB_BACKUP_HEALTH_PORT:-8081}:8080"

    volumes:
      - ${SURREALDB_BACKUP_PATH:-./backups}:/backups
      - syno_core_keyvault:/keyvault:ro
      - syno_core_logs:/logs
      - ../../apps/syno-core/scripts/backup:/scripts:ro

    command: ["/scripts/backup-entrypoint.sh"]

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: ${SURREALDB_BACKUP_MEMORY_LIMIT:-256M}
        reservations:
          memory: ${SURREALDB_BACKUP_MEMORY_RESERVATION:-128M}

    networks:
      - syno-core-network

    labels:
      - "traefik.enable=false"
      - "com.synology.surrealdb-backup.description=SurrealDB automated backup service"
      - "com.synology.surrealdb-backup.category=backup"
      - "com.synology.surrealdb-backup.scope=core"

networks:
  syno-core-network:
    external: true

volumes:
  syno_core_keyvault:
    external: true
  syno_core_logs:
    external: true