# ===========================================
# DATABASE SERVICES
# ===========================================

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: core-surrealdb
    restart: unless-stopped

    depends_on:
      - doppler

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}

    ports:
      - "${SURREALDB_PORT:-8001}:8000"

    volumes:
      - ${SURREALDB_DATA_PATH:-/volume1/docker/core/surrealdb/data}:/data
      - ${SURREALDB_CONFIG_PATH:-./config/surrealdb}:/config
      - syno_core_keyvault:/keyvault:ro
      - ./scripts:/scripts:ro

    command: ["/bin/bash", "/scripts/surrealdb-start.sh"]

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    deploy:
      resources:
        limits:
          memory: ${SURREALDB_MEMORY_LIMIT:-1G}
        reservations:
          memory: ${SURREALDB_MEMORY_RESERVATION:-512M}

    networks:
      - syno-core-network

    labels:
      - "traefik.enable=false"
      - "com.synology.core.surrealdb.description=SurrealDB multi-model database"
      - "com.synology.core.surrealdb.category=storage"

networks:
  syno-core-network:
    external: true

volumes:
  syno_core_keyvault:
    external: true
  syno_core_surrealdb_data:
    external: true