# ===========================================
# BASE INFRASTRUCTURE
# ===========================================
# Shared networks, volumes, and base configuration

networks:
  core-network:
    driver: bridge
    name: core-network
    driver_opts:
      com.docker.network.bridge.name: core-bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  # Portainer data volume
  core_portainer_data:
    name: core_portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PORTAINER_DATA_PATH:-/volume1/docker/core/portainer/data}
  
  # SurrealDB data volume
  core_surrealdb_data:
    name: core_surrealdb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SURREALDB_DATA_PATH:-/volume1/docker/core/surrealdb/data}
  
  # Core keyvault volume for all services
  core_keyvault:
    name: core_keyvault
    driver: local