# ===========================================
# BASE INFRASTRUCTURE
# ===========================================

networks:
  syno-core-network:
    driver: bridge
    name: syno-core-network
    driver_opts:
      com.docker.network.bridge.name: core-bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

volumes:
  syno_core_portainer_data:
    name: syno_core_portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PORTAINER_DATA_PATH:-/volume1/docker/syno-core/portainer/data}

  syno_core_surrealdb_data:
    name: syno_core_surrealdb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SURREALDB_DATA_PATH:-/volume1/docker/syno-core/surrealdb/data}

  syno_core_keyvault:
    name: syno_core_keyvault
    driver: local