# ===========================================
# SECRETS MANAGEMENT SERVICE
# ===========================================
# Doppler-based centralized secrets management

services:
  doppler:
    build:
      context: ./doppler
      dockerfile: Dockerfile
    image: synology-nas/doppler-alpine:latest
    container_name: core-doppler
    restart: unless-stopped

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=${DOPPLER_PROJECT:-core-services}
      - DOPPLER_CONFIG=${DOPPLER_CONFIG:-dev}

    healthcheck:
      test: ["CMD", "doppler", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

    networks:
      - syno-core-network

    labels:
      - "com.synology.core.doppler.description=Secrets management service"
      - "com.synology.core.doppler.category=security"

    volumes:
      - syno_core_keyvault:/keyvault
      - ./scripts:/scripts:ro

    command: ["/bin/bash", "/scripts/doppler-keyvault-init.sh"]

networks:
  syno-core-network:
    external: true

volumes:
  syno_core_keyvault:
    external: true