# ===========================================
# SYNO-CORE - MODULAR ORCHESTRATION
# ===========================================

include:
  - ../../shared/infrastructure.yml
  - ../../shared/secrets.yml
  - ../../modules/services/portainer/docker-compose.yml
  - ../../modules/services/surrealdb/docker-compose.yml
  - ../../modules/services/azurite/docker-compose.yml
  - ../../modules/services/azure-cli/docker-compose.yml

# ===========================================
# SERVICE DEPENDENCY AND CONFIGURATION OVERRIDES
# ===========================================

x-global-labels: &global-labels
  com.synology.stack: "syno-core"
  com.synology.version: "1.0.0-modular"
  com.synology.architecture: "modular"
  com.synology.managed-by: "docker"
