# ===========================================
# MANAGEMENT SERVICES
# ===========================================

services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: core-portainer
    restart: unless-stopped

    depends_on:
      - doppler

    command: ["/bin/bash", "/scripts/portainer-start.sh"]

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}

    ports:
      - "${PORTAINER_PORT:-9000}:9000"
      - "${PORTAINER_EDGE_PORT:-8000}:8000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH:-/volume1/docker/syno-core/portainer/data}:/data
      - /volume1/docker:/var/lib/docker/volumes:ro
      - syno_core_keyvault:/keyvault:ro
      - ./scripts:/scripts:ro

    deploy:
      resources:
        limits:
          memory: ${PORTAINER_MEMORY_LIMIT:-512M}
        reservations:
          memory: ${PORTAINER_MEMORY_RESERVATION:-256M}

    networks:
      - syno-core-network

    labels:
      - "traefik.enable=false"
      - "com.synology.core.portainer.description=Docker container management UI"
      - "com.synology.core.portainer.category=management"

networks:
  syno-core-network:
    external: true

volumes:
  syno_core_keyvault:
    external: true
  syno_core_portainer_data:
    external: true