# ===========================================
# SECRETS MANAGEMENT SERVICE
# ===========================================
# Doppler-based centralized secrets management

services:
  doppler:
    build:
      context: ./doppler
      dockerfile: Dockerfile
    image: synology-nas/doppler-alpine:latest
    container_name: core-doppler
    restart: unless-stopped
    
    # Environment variables
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      - DOPPLER_PROJECT=${DOPPLER_PROJECT:-core-services}
      - DOPPLER_CONFIG=${DOPPLER_CONFIG:-dev}
    
    # Health check
    healthcheck:
      test: ["CMD", "doppler", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    
    # Network configuration
    networks:
      - core-network
    
    # Labels for organization
    labels:
      - "com.synology.core.doppler.description=Secrets management service"
      - "com.synology.core.doppler.category=security"
    
    # Volume mounts for keyvault and scripts
    volumes:
      - core_keyvault:/keyvault
      - ./scripts:/scripts:ro
    
    # Use external script for cleaner maintenance
    command: ["/bin/bash", "/scripts/doppler-keyvault-init.sh"]

# Use external networks and volumes
networks:
  core-network:
    external: true

volumes:
  core_keyvault:
    external: true