# ===========================================
# CENTRALIZED SECRETS MANAGEMENT
# ===========================================
# Doppler-based centralized secrets for core services via keyvault volume

services:
  doppler-core:
    build:
      context: ../modules/components/doppler
      dockerfile: Dockerfile
    image: synology-nas/doppler-alpine:latest
    container_name: doppler-core
    restart: unless-stopped

    environment:
    - PUID=${PUID:-1000}
    - PGID=${PGID:-1000}
    - TZ=${TZ:-UTC}
    - DOPPLER_TOKEN=${DOPPLER_TOKEN}
    - DOPPLER_PROJECT=${DOPPLER_PROJECT:-core-services}
    - DOPPLER_CONFIG=${DOPPLER_CONFIG:-dev}

    healthcheck:
      test: [ "CMD", "doppler", "--version" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

    volumes:
    - syno_core_keyvault:/keyvault
    - ../apps/syno-core/scripts:/scripts:ro

    networks:
    - syno-core-network

    labels:
    - "com.synology.core.doppler.description=Centralized secrets management"
    - "com.synology.core.doppler.category=security"
    - "com.synology.core.doppler.scope=infrastructure"

    command: [ "/bin/bash", "/scripts/doppler-keyvault-init.sh" ]
