services:
  doppler-portainer:
      build: ../doppler
      container_name: doppler-portainer
      environment:
        - DOPPLER_TOKEN=${DOPPLER_TOKEN}
      volumes:
        - vault:/vault
      command:
        - /bin/bash
        - -c
        - |
          echo 'Starting Doppler secret sync...'
          mkdir -p /vault
          chmod 755 /vault
          doppler run -- /bin/bash -c 'printf "%s" "$$PORTAINER_ADMIN_PASSWORD" > /vault/portainer_admin_password'
          echo 'Doppler sync complete. Keeping container alive...'
          tail -f /dev/null
      restart: unless-stopped
      networks:
        - portainer_network

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    
    command:
      - -H
      # Security and local network access only
      - unix:///var/run/docker.sock
      # Portainer Secret
      - --admin-password-file
      - /run/vault/portainer_admin_password
    
    # Environment variables
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      
    # Port mapping - local network access only
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
      - "${PORTAINER_EDGE_PORT:-8000}:8000"
    
    # Volume mappings optimized for Synology NAS
    volumes:
      # Docker socket for container management
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH:-./data}:/data
      - /volume1/docker:/var/lib/docker/volumes:ro
      - vault:/run/vault:ro

    depends_on:
      - doppler-portainer
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Network configuration
    networks:
      - portainer_network

    labels:
      - "traefik.enable=false"
      - "com.synology.portainer.description=Docker container management UI"
      - "com.synology.portainer.category=management"

# Networks
networks:
  portainer_network:
    driver: bridge
    name: portainer_network

# Volumes
volumes:
  data:
    name: portainer_data
    driver: local
  vault:
    name: vault
    driver: local