networks:
  website-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/28
          gateway: 172.11.0.1

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__API_KEY=
    volumes:
      - qdrant-storage:/qdrant/storage
    networks:
      website-network:
        ipv4_address: 172.11.0.2

  ollama:
    image: ollama/ollama
    container_name: ollama
    environment:
      - OLLAMA_ORIGINS=*
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      website-network:
        ipv4_address: 172.11.0.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  qdrant-storage:
  ollama-data: