# ===========================================
# AZURITE SERVICE
# ===========================================
# Azure Storage Emulator for local development and testing
# Provides blob, queue, and table storage endpoints

services:
  azurite:
    build:
      context: ../../components/azurite
      dockerfile: Dockerfile
    image: synology-nas/azurite:latest
    container_name: azurite
    restart: unless-stopped

    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - AZURITE_ACCOUNTS=${AZURITE_ACCOUNTS:-synology:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==}
      - AZURITE_LOCATION=${AZURITE_LOCATION:-./azurite_data}
      - AZURITE_ENABLE_ACCESS_LOG=${AZURITE_ENABLE_ACCESS_LOG:-true}
      - AZURITE_ENABLE_DEBUG_LOG=${AZURITE_ENABLE_DEBUG_LOG:-false}
      - AZURITE_SSL=${AZURITE_SSL:-false}
      - AZURITE_BLOB_PORT=${AZURITE_BLOB_PORT:-10000}
      - AZURITE_QUEUE_PORT=${AZURITE_QUEUE_PORT:-10001}
      - AZURITE_TABLE_PORT=${AZURITE_TABLE_PORT:-10002}

    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"    # Blob service
      - "${AZURITE_QUEUE_PORT:-10001}:10001"   # Queue service
      - "${AZURITE_TABLE_PORT:-10002}:10002"   # Table service

    volumes:
      - ${AZURITE_DATA_PATH:-./data}:/data
      - syno_core_keyvault:/keyvault:ro
      - syno_core_logs:/logs

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:10000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: ${AZURITE_MEMORY_LIMIT:-256M}
        reservations:
          memory: ${AZURITE_MEMORY_RESERVATION:-128M}

    networks:
      - syno-core-network

    labels:
      - "traefik.enable=false"
      - "com.synology.azurite.description=Azure Storage Emulator"
      - "com.synology.azurite.category=storage"
      - "com.synology.azurite.ports=10000-10002"

    command: [
      "azurite",
      "--blobHost", "0.0.0.0",
      "--queueHost", "0.0.0.0",
      "--tableHost", "0.0.0.0",
      "--location", "/data",
      "--debug", "/logs/azurite.log"
    ]

networks:
  syno-core-network:
    external: true

volumes:
  syno_core_keyvault:
    external: true
  syno_core_logs:
    external: true